// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using StoreRobot.Models;

#nullable disable

namespace StoreRobot.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220524072934_AddDkpc")]
    partial class AddDkpc
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("StoreRobot.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Dkpc")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPakhshOff")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSafirOff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PakhshPriceInOff")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReferencePrice")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SafirPriceInOff")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Sku")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("StokeQuantity")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserPrice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Products");
                });

            modelBuilder.Entity("StoreRobot.Models.ProductErrors", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SKU")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Store")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ProductErrors");
                });
#pragma warning restore 612, 618
        }
    }
}
